name: localization workflow 

on: [pull_request]

jobs:
  create-ticket:
    if: ${{ contains(github.event.pull_request.head.ref, 'release') }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: echo ${{ github.event.pull_request.head.ref }}
      - run: yarn create-ticket 
        env:
          GITHUB_EVENT: ${{ toJSON(github.event.pull_request) }}

